### PR TITLE
WIP: Bump PHP requirement to 7.4 and exchange portable text handling with a separate package

### PR DESCRIPTION
**Pull request by christeredvartsen**
This pull request bumps the minimum PHP requirement to 7.4. This is the minimum version that still has security support (https://www.php.net/supported-versions.php).

All other dependencies have also been bumped to their latest respective versions. The test suite needed some changes because of this, notably:

- Use `setUp` instead of `__construct`
- Change exception annotations to code as the annotations are no longer supported

I also took the liberty of swapping out [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) for [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer). This tool can easily be used to automatically fix code on save in editors for instance.

### CODE REVIEW

**Comment by christeredvartsen** [comment]
A few other thoughts when we are breaking BC anyways:

- Rename `./lib` to `./src` which is a more common folder name used for the source in PHP projects
- Rename `./test` to `./tests` (same as above)
- Rename the composer package to `sanity/sanity` (or `sanity-io/sanity`)

The last one might cause some issues, but makes more sense than having `-php` in the package name. The repo name should remain the same though.

**Comment by rexxars** [comment]
Thanks a bunch! I feel like all of the changes you propose makes sense - would you mind taking a stab at those, too?

**Comment by christeredvartsen** [comment]
> would you mind taking a stab at those, too?

Sure. What do you want the new package name to be? `sanity/sanity` or `sanity-io/sanity`?

We should also do a final release of the existing package, marking it as abandoned, and referring to the new package. That way people who require `sanity/sanity-php` will get a message saying it's abandoned in favour of the new package.

**Comment by rexxars** [comment]
> Sure. What do you want the new package name to be? `sanity/sanity` or `sanity-io/sanity`?

`sanity/sanity` feels right to me.

**Comment by christeredvartsen** [comment]
`./lib` and `./test` have been renamed to `./src` and `./tests` respectively.

Also, the package has been renamed to `sanity/sanity`. Once this PR is merged to the `main`-branch you should [submit the package](https://packagist.org/packages/submit) to Packagist. Remember to enable auto-updates.

After that has been done you can [mark the old package as abandoned](https://packagist.org/packages/sanity/sanity-php/abandon?), and refer to this one as the replacement.

**Review by rexxars — APPROVED** [review]
Many thanks!

**Comment by christeredvartsen** [comment]
Since this is a breaking change we want to do a bit more damage while we're at it. We will split out the portable text part of the as a separate package over at https://github.com/portabletext, and make the client use the new package instead.

**Pull request closed without merging**
